#!/bin/bash
# CiteWeave Deployment Setup Script
# This script helps configure CiteWeave for deployment on different machines

set -euo pipefail

echo "🚀 CiteWeave Deployment Setup"
echo "=============================="

# Get project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

# Check if .env already exists
if [[ -f ".env" ]]; then
    echo "⚠️  .env file already exists. Do you want to overwrite it? (y/N)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo ""
echo "📁 Configuring data directories..."

# Create necessary directories
mkdir -p data logs documents

echo "✅ Created directories: data/, logs/, documents/"

echo ""
echo "🔧 Configuring environment variables..."

# Generate .env file
cat > .env << EOF
# CiteWeave Environment Configuration
# Generated by setup_deployment.sh

# Application Configuration
CITEWEAVE_API_HOST=0.0.0.0
CITEWEAVE_API_PORT=31415
CITEWEAVE_ENV=production

# Data Directory Configuration (relative to project root)
CITEWEAVE_DATA_DIR=./data
CITEWEAVE_LOGS_DIR=./logs

# External Service URLs (update these for your deployment)
QDRANT_URL=http://localhost:6333
GROBID_URL=http://localhost:8070
NEO4J_URI=bolt://localhost:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=12345678

# Document Watch Configuration
# Add your document directories here (relative paths recommended)
DOCS_WATCH_DIRS=./documents

# Optional: Custom paths for different environments
# Uncomment and modify as needed:
# CITEWEAVE_CUSTOM_DOCS_PATH=\${HOME}/Documents/research
# CITEWEAVE_CUSTOM_DATA_PATH=\${PWD}/data
EOF

echo "✅ Generated .env file"

echo ""
echo "📋 Configuration Summary:"
echo "   Data Directory: ./data"
echo "   Logs Directory: ./logs"
echo "   Documents Directory: ./documents"
echo "   API Port: 31415"
echo ""
echo "🗄️  Database files (using .sqlite extension):"
echo "   data/logs/query_traces.sqlite    # Query trace logs"
echo "   data/state.sqlite                # Application state"
echo "   data/author_paper_index.sqlite   # Author-paper index"
echo ""

echo "🔍 Next steps:"
echo "1. Review and customize .env file if needed"
echo "2. Add your documents to the documents/ directory"
echo "3. Run: ./run.sh --rebuild"
echo "4. Access CiteWeave at: http://localhost:31415"
echo ""

echo "🎉 Setup completed successfully!"
echo "   You can now deploy CiteWeave on any machine by:"
echo "   - Copying this project directory"
echo "   - Running this setup script"
echo "   - Customizing .env for your environment"
